image: gradle:8.8-jdk21-alpine

stages:
  - build
  - test
  - check_code_coverage
  - publish-release

variables:
  GITLAB_PRIVATE_TOKEN: ${GITLAB_TOKEN}

build-job:
  stage: build
  interruptible: true
  script:
    - gradle clean build
  artifacts:
    when: on_success
    access: all
    expire_in: 15 minutes
    paths:
      - build

test-job:
  stage: test
  interruptible: true
  script:
    - gradle test
  artifacts:
    when: always
    access: all
    expire_in: 15 minutes
    paths:
      - build/test-results
    reports:
      junit: build/test-results/**/*.xml

coverage-job:
  stage: check_code_coverage
  interruptible: true
  script:
    - gradle jacocoTestCoverageVerification

publish-release:
  stage: publish-release
  script:
    - gradle publish
  only:
    refs:
      - main